package br.com.correios.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-01-28T19:18:23.645-02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CalcPrecoPrazoWSHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CalcPrecoPrazoWSHttpPost {

    @WebMethod(operationName = "CalcPrecoPrazoData")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoPrazoData(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrecoPrazoRestricao")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoPrazoRestricao(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrazoRestricao")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrazoRestricao(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrecoFAC")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoFAC(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "strDataCalculo", name = "strDataCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String strDataCalculo
    );

    @WebMethod(operationName = "CalcPreco")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPreco(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento
    );

    @WebMethod(operationName = "CalcPrecoData")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoData(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrazo")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrazo(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino
    );

    @WebMethod(operationName = "CalcPrazoData")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrazoData(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrecoPrazo")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoPrazo(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento
    );
}
