package br.com.correios.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-01-28T19:18:23.466-02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CalcPrecoPrazoWSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CalcPrecoPrazoWSSoap {

    @WebMethod(operationName = "CalcPrecoPrazoData", action = "http://tempuri.org/CalcPrecoPrazoData")
    @RequestWrapper(localName = "CalcPrecoPrazoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoData")
    @ResponseWrapper(localName = "CalcPrecoPrazoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoDataResponse")
    @WebResult(name = "CalcPrecoPrazoDataResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrecoPrazoData(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrecoPrazoRestricao", action = "http://tempuri.org/CalcPrecoPrazoRestricao")
    @RequestWrapper(localName = "CalcPrecoPrazoRestricao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoRestricao")
    @ResponseWrapper(localName = "CalcPrecoPrazoRestricaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoRestricaoResponse")
    @WebResult(name = "CalcPrecoPrazoRestricaoResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrecoPrazoRestricao(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrazoRestricao", action = "http://tempuri.org/CalcPrazoRestricao")
    @RequestWrapper(localName = "CalcPrazoRestricao", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoRestricao")
    @ResponseWrapper(localName = "CalcPrazoRestricaoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoRestricaoResponse")
    @WebResult(name = "CalcPrazoRestricaoResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrazoRestricao(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrecoFAC", action = "http://tempuri.org/CalcPrecoFAC")
    @RequestWrapper(localName = "CalcPrecoFAC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoFAC")
    @ResponseWrapper(localName = "CalcPrecoFACResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoFACResponse")
    @WebResult(name = "CalcPrecoFACResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrecoFAC(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(name = "strDataCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String strDataCalculo
    );

    @WebMethod(operationName = "CalcPreco", action = "http://tempuri.org/CalcPreco")
    @RequestWrapper(localName = "CalcPreco", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPreco")
    @ResponseWrapper(localName = "CalcPrecoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoResponse")
    @WebResult(name = "CalcPrecoResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPreco(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento
    );

    @WebMethod(operationName = "CalcPrecoData", action = "http://tempuri.org/CalcPrecoData")
    @RequestWrapper(localName = "CalcPrecoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoData")
    @ResponseWrapper(localName = "CalcPrecoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoDataResponse")
    @WebResult(name = "CalcPrecoDataResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrecoData(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrazo", action = "http://tempuri.org/CalcPrazo")
    @RequestWrapper(localName = "CalcPrazo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazo")
    @ResponseWrapper(localName = "CalcPrazoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoResponse")
    @WebResult(name = "CalcPrazoResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrazo(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino
    );

    @WebMethod(operationName = "CalcPrazoData", action = "http://tempuri.org/CalcPrazoData")
    @RequestWrapper(localName = "CalcPrazoData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoData")
    @ResponseWrapper(localName = "CalcPrazoDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrazoDataResponse")
    @WebResult(name = "CalcPrazoDataResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrazoData(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    @WebMethod(operationName = "CalcPrecoPrazo", action = "http://tempuri.org/CalcPrecoPrazo")
    @RequestWrapper(localName = "CalcPrecoPrazo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazo")
    @ResponseWrapper(localName = "CalcPrecoPrazoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcPrecoPrazoResponse")
    @WebResult(name = "CalcPrecoPrazoResult", targetNamespace = "http://tempuri.org/")
    public br.com.correios.soap.CResultado calcPrecoPrazo(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.math.BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento
    );
}
